# Generated by Django 2.1.15 on 2021-03-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lawyer',
            new_name='Lawyers',
        ),
    ]
