# Generated by Django 2.1.15 on 2021-03-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaster', '0002_auto_20210302_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyers',
            old_name='biography',
            new_name='bio',
        ),
    ]
