# Generated by Django 2.1.15 on 2021-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaster', '0004_auto_20210302_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='field',
            field=models.CharField(default='nothing', max_length=150),
            preserve_default=False,
        ),
    ]
