# Generated by Django 2.1.15 on 2021-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmaster', '0006_lawyers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyers',
            name='img',
            field=models.ImageField(upload_to='lawyers'),
        ),
    ]
